version: '3'
services:
  express-server:
    image: dorayaki
    ports:
      - '5000:5000'
    depends_on:
      - mongo
    networks:
      - backend-app
  mongo:
    image: mongo:3.6.19-xenial
    ports:
      - '27017:27017'
    networks:
      - backend-app
    volumes:
      - mongo-data:/data/db
networks:
  backend-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local
